### ISSUE TITLE
Add an internalization feature so that site can be used in espanol.

### ISSUE THREAD

**Issue by brianek** [codefordc/expungement-dc#106]
Step 1: Create a banner/button  four our site that reads "espanol" that is show on the first 3 pages of the site. 
Step 2: Fork the cleanslate site and host on your github pages. We will then use the link of your github pages to be used as the link references as "espanol".

**Comment by DavidGinzberg** [comment]
@brianek Is there a particular reason we are looking at doing this on a separate repo rather than just adding an internationalization feature?

**Comment by brianek** [comment]
No reason. Whatevery works.

**Comment by brianek** [comment]
@davidginzberg

**Comment by brianek** [comment]
Here is the first part of the translation in spanish: https://docs.google.com/document/d/1s6QXDZzezCAOVszPB2zpRWGjHY68H42n6-4p9LqJdJE/edit?usp=sharing

**Comment by brianek** [comment]
@mkalish

**Comment by brianek** [comment]
example: http://www.expunge.io/

**Comment by rdeprey** [comment]
Depending on how the backend is set-up, we might be able to use the angular-translate module to provide translations: http://www.sitepoint.com/multilingual-support-for-angularjs/?utm_source=javascriptweekly&utm_medium=email.  Basically, we'd have one json file in English and another in Spanish and would use the module to manage them.  

Here's more information on the angular-translate model itself: https://angular-translate.github.io/

**Comment by mkalish** [comment]
Hey everyone meant to respond to this earlier, but the past month has been crazy.  I had submitted a PR a month ago using angular translate...I'll dig up the code, add the new translations and submit another PR this weekend.

**Comment by brianek** [comment]
Mkalish. Great

**Comment by brianek** [comment]
We have decided to just partner with a legal clinic that services spanish professional (this is not set in stone) @mkalish Is there anything else you are interested in working on?
