### ISSUE TITLE
Imrpove user experience of site. Front end design. Estimated work time: 1 hour or less. 

### ISSUE THREAD

**Issue by brianek** [codefordc/expungement-dc#107]
Our site has a few differnt users: Lawyers/Law students, returning citizens (those with criminal or arrest records) and other (case managers, family members etc). 

We want to be ask at the beginning of the site  who that person is. For example, it could be 3 buttons and we ask the user to click which one they are. I..e  Option 1: lawyer/law sudent 2) returning citizen/formerly incarcerated, 3) case manager, 4) family member of formely incarcerated.  

Our hope is tha thtis will allow us to track who is using the site better. We also will be able to change the language so its more affirming. For example, if the person using the site is a lawyer trying to help a client, we can change the language to ask, "does your client have their criminal record now" as opposed to saying "do you have your cirminal record now).

**Comment by brianek** [comment]
Welcome Page
Mobile
Lots of wasted space in hamburger, font is small . Can disclaimer be shrunk/condensed, like a Wikipedia sub page?
Can disclaimer be shrunk/condensed, like a Wikipedia sub page?
Text looks overwhelming, any bolding or formatting to break it up? linking out to affiliated organizations/contact (PDSDC) and menu options
Bold button?
include disclaimer in hamburger
Shorten up language as much as possible on home page
linking out to affiliated organizations/contact (PDSDC) and menu options

Page 1
Mobile
Spacing looks fine. On PC space needs trimming. 

Page 2
Mobile
Text gets pretty bulky really quick; The meaning of legal words is a great idea, but the feature needs to define the text NOT in legalese (e.g. Jurisdiction: "the legal authority of the court to hear and decide a certain type of case" &shrug
Would there be a way to contract/expand the information available? E.g. subbing "I was arrested in DC b/c I had a warrant in another jurisdiction" to "I was arrested in DC…" and clicking  "…" to reveal the rest of the text
^^ will reduce scrolling needed, especially if it's click thru, not hover over

Would it be possible to have a main menu that divvies up the users into "Returning Citizen", "Lawyer", and "Social Worker"? Not sure how useful the "Lawyer" portion would be, since we're deciphering their work, but having the Returning Citizen and Social Worker option would lend to a more succinctly crafted webpage

http://www.cleanslatedc.com/#/eligibility/531
Mobile
Eligibility page is horribly confusing/unorganized
confused by filter term option /doesn't work 
Filter term option accepts only EXACT search terms (e.g. "Possesison of Pistol" yields correct term,but not "gun" or "posesion gun")
long, long list of misdemeanors and hard to keep track. Could there maybe be a bubble list where you select certain offenses

**Comment by brianek** [comment]
Change intial menu page that expands when clicked on: 
1) Incorrect criminal record
2) Seal non-conviction
3) seal conviction
4) arrest & warrant in another jurisdiction
5) seal arrest -no conviction
6) Marijuana

**Comment by brianek** [comment]
Resources: 
http://jsfiddle.net/8MXAu/
http://blog.templatemonster.com/2014/06/27/click-to-expand-paragraph-text-with-jquery/
http://designgala.com/how-to-expand-collapse-toggle-div-layer-using-jquery/

**Comment by brianek** [comment]
Accordion javascript: http://www.elated.com/articles/javascript-accordion/

**Comment by brianek** [comment]
Here is visualization of how it could look. But feel free to use your own creativiity.
![slide1](https://cloud.githubusercontent.com/assets/9157639/9150540/df2eb026-3dab-11e5-929d-596d3d21563d.jpg)
![slide2](https://cloud.githubusercontent.com/assets/9157639/9150541/df2ede16-3dab-11e5-863c-29cf30db2ed7.jpg)
![slide3](https://cloud.githubusercontent.com/assets/9157639/9150538/df2d5c44-3dab-11e5-8ba6-ce7fdbe6f069.jpg)
![slide4](https://cloud.githubusercontent.com/assets/9157639/9150539/df2e87ea-3dab-11e5-99ea-bd537cc2d539.jpg)

**Comment by brianek** [comment]
[Presentation5.pdf](https://github.com/codefordc/clean-slate/files/1265/Presentation5.pdf)

**Comment by ParentJA** [comment]
@brianek I'm not sure what needs to be done here. Will you provide clearer instructions, including what links to click on in order to see the defect? What is the "initial menu page" for example? Thanks!

**Comment by brianek** [comment]
@ParentJA Sorry about the confusion. I made a video that is less than 4 minutes and explains everything. http://youtu.be/yRIG2To4V5U

**Comment by rdeprey** [comment]
@brianek I saw in the video where you wanted to move the disclaimer into an accordion menu, so I submitted a pull request with that change.  I'm going to try to help with some of the other UX items this weekend.

**Comment by rdeprey** [comment]
@brianek I adjusted the UI to add the new audience question and changed the categories for sealing records from buttons to using the accordion menu.  For the new audience question, I wasn't sure where to add the textbox to capture comments if a user selects "Other" though.  What do you think about making those radio buttons instead?  It would make it easier to add the textbox.  Then, we could add a continue button that could get the next step based on the item selected.

**Comment by brianek** [comment]
Sure. Radio button would work. @rdeprey

**Comment by brianek** [comment]
From a UX perspective, I am also thinking about removing the "other" option

**Comment by brianek** [comment]
@rdeprey. Whats your opinion on that? If you support use of the "other" option  then feel free to implement the radio buttons.

**Comment by rdeprey** [comment]
@brianek Yeah, I'm not sure about the Other option because it will be hard to use it to target the language.  I guess you could collect the data from it though and use it for future improvements.

**Comment by brianek** [comment]
@rdeprey Sounds like  a plan. So yes to turning tthem into radio buttons.
