### ISSUE TITLE
Review these similar projects and resource sites for inspiration: 

### ISSUE THREAD

**Issue by rebeccawilliams** [codefordc/expungement-dc#11]
expungement / sealing (other locations, but example workflows):
- http://www.expungemaryland.org/
- https://lawstudents.neotalogic.com/a/expungement2-1
- http://expunge.io 

dc services/summaries:
- forms: http://secure.uslegalforms.com/cgi-bin/forms/search.pl?state=DC&field=anywhere&rating=all&query=expungement&altform=&memform=&topic=
- lawyers: http://www.criminaldefenselawyer.com/path/min-path2
- dc site: http://orca.dc.gov/service/record-sealing-and-expunging
- guide: http://koehlerlaw.net/other-offenses/expungementsealing-of-criminal-records/

**Comment by brianek** [comment]
Thanks
