### ISSUE TITLE
Add a alert/pop-up (using javascript button to this page that says "Answer the following questions based on only 1 arrest or charge at a time).

### ISSUE THREAD

**Issue by brianek** [codefordc/expungement-dc#127]
Edit this page: https://www.cleanslatedc.com/#/eligibility/602

Change the question from:   "Select the type of conviction you would like to seal on your D.C. record."

To : "Select one conviction on your record. Is that a conviction for a felony conviction or misdemeanor conviction?

**Comment by omarimayerswalker** [comment]
I'll work on this.

**Comment by brianek** [comment]
Hi: this one sort of got taken care of.

**Comment by brianek** [comment]
But it can be improved
