### ISSUE TITLE
Add 'What Must You Disclose After Having Your Criminal Record Sealed in D.C.?' resources/tips

### ISSUE THREAD

**Issue by rebeccawilliams** [codefordc/expungement-dc#13]
e.g. http://koehlerlaw.net/2014/05/the-effect-of-sealing-a-criminal-record-in-d-c/

**Comment by brianek** [comment]
Hi Rebecca. Let me know if you want to work on this part. This language is very dense and we would love to create this as a separate instructional page or quiz (multiple choice) or video specifically dedicated to: "So, you've sealed your record, now what."
