### ISSUE TITLE
Many changes needed to fix the list of ineliigble  misdemeanors page: vhttps://www.cleanslatedc.com/#/eligibility/531

### ISSUE THREAD

**Issue by brianek** [codefordc/expungement-dc#130]
1)  delete the following crimes from this page "Interpersonal vilence, intimate partner violence, intra family violence"

2) edit the file to now say:
*This is a list of crimes that, if you have them, may result in a judge denying your request to seal your record. 
FELONY:
A  Felony that is not  a charge for Failuer to not appear (FTA)
MISDEMEANORS
...Insert list of misdemeanors
2)) Add an additional question if the person answers no to this page. That additional question should ask. "Were you  arrested or charged with a misdemeanor of felony that involved assualting someone you know (i.e. a family member/spouse)?"

**Comment by brianek** [comment]
HIGHEST PRIORITY

**Comment by rdeprey** [comment]
@brianek I removed the search bar/filter term feature, but wasn't sure how to do the rest without possibly affecting other pages, so I left those alone.  I submitted a pull request that includes this.

**Comment by brianek** [comment]
no worries. I will look into it.

**Comment by jmezetin** [comment]
How will the routing of the pages changes with this new question?
No & No
No & Yes
Yes & Yes
Yes & No

**Comment by brianek** [comment]
@jmezetin. The routing of the page will be like this:
Question: are any of these crimes on this list your crime?
No: ask them a new: question #52
Yes: should go to this question:
https://www.cleanslatedc.com/#/eligibility/560

Question 52: Were you arrested or charged with the  crime
of assualt (either a misdemeanor or  felony)against a family member or
spouse?
No: https://www.cleanslatedc.com/#/eligibility/532.
Yes: https://www.cleanslatedc.com/#/eligibility/560

Does this make sense?
