### ISSUE TITLE
For every end state that tells a person they are inelgible for sealing, add in information on Ban the Box. 

### ISSUE THREAD

**Issue by brianek** [codefordc/expungement-dc#132]
1) add in this language: Even though you are not eligible for sealing your criminal record,  In 2014 The District of Columbia passed a  law that prohibits employers (with 11 or more employees) from having a criminal background questions on a job application form, and  ALSO prohibits an employer from asking about criminal convictions, arrests or accusations until after a conditional offer of employment has been made.  We encourage you to learn more about how to submite a complaint about violations of the law to the DC Office of Human Rights (OHR) here[ INSERT LINK: http://ohr.dc.gov/page/returningcitizens]. Compensation may be available to you if it is found that an employer you applied for a job with asked about your criminal history before making a condition offer of employment OR if they have a question on their employment application that asks if you have every committed a crime or been arrested. 

2) embed this video to appear below the language above: <iframe width="560" height="315" src="https://www.youtube.com/embed/BFBzPX3VncI" frameborder="0" allowfullscreen></iframe>

**Comment by jmezetin** [comment]
For part 2, what video needs to be embedded?

**Comment by brianek** [comment]
I still need a make it and wont finish till tonight. But I will take over
making the video. No worries.
