### ISSUE TITLE
Possible workflow to consider

### ISSUE THREAD

**Issue by rebeccawilliams** [codefordc/expungement-dc#14]
Below is cribbed heavily from: http://koehlerlaw.net/other-offenses/expungementsealing-of-criminal-records/
### Prologue: Why should I seal my criminal record?
- Describe the benefits and the difference between expungement and sealing criminal records. Point to other state recourses too?
### **Step 1: Obtain copy of criminal record**
- Note price, time it takes to obtain, and online and offline way to obtain certified and uncertified copies. Note law: D.C. Code § 2-1402.66  
### **Step 2: Determine if you are eligible for sealing your criminal record**

| Status | Years After When You're Eligible to File A Motion to Seal | How | Law |
| --- | --- | --- | --- |
| Sealing An Arrest Record On The Grounds Of Actual Innocence | Anytime, but the standard of review changes after 4 years. | File a motion to seal on the grounds of actual innocence.  Available for Any type of offense – felony or misdemeanor. The standard of review for a judge considering the motion is a preponderance of the evidence (i.e., more likely than not) if filed within 4 years of the date the prosecution was terminated. If the motion is filed beyond 4 years of this date, the evidence must be clear and convincing; that is, evidence that is highly probable or reasonably certain. | D.C. Code § 16-802 |
| Sealing An Arrest Record | 2 years for eligible misdemeanors, 3 years for [ineligible misdemeanors](http://dccode.org/simple/sections/16-801.html) that were never papered, and 4 years for every other offense. | File a motion to seal after the required time period. Any open charges or prior convictions would render the person ineligible for relief. For cases involving "eligible misdemeanors" ([see ineligible misdemeanors here](http://dccode.org/simple/sections/16-801.html)), the burden is on the prosecution to establish by a preponderance of the evidence that it is not in the interests of justice to grant relief. For every other offense, the burden is on the person filing the motion to prove by a preponderance of the evidence that it is in the interests of justice to grant the motion. | D.C. Code § 16-803 |
| Sealing A Conviction | 8 years after completion of sentence for eligible misdemeanors ([see ineligible misdemeanors](http://dccode.org/simple/sections/16-801.html)) and felony violation under the Bail Reform Act. | File a motion to seal after the required time period.  Any open charges or prior convictions would render the person ineligible for relief. The burden is on the person filing the motion to establish by clear and convincing evidence that it is in the interest of justice for the judge to grant relief. | D.C. Code § 16-803 |
| Sealing of Juvenile Records | 2 years after being released from court supervision, AND you cannot have been subsequently convicted of a crime or adjudicated delinquent/in need of supervision. | File a motion to have all records associated with the case sealed. | D.C. Code § 16-2335. |
### **Step 3: Paperwork**
- Link to form and lawyer resources, with prices when available.
### Epilogue: What must you disclose after having your criminal record sealed?
- Sealing An Arrest Record On The Grounds Of Actual Innocence: The effect of a judge granting this motion is to "restore" the person who filed the motion to the "status he or she occupied before being arrested or charged." ÃÂ In other words, if ever asked by anyone for any purpose whether or not he/she has ever been arrested or charged with a crime, the person can honestly and legally say so no. D.C. Code § 16-802.
- Sealing An Arrest Record: If the motion to seal is granted under these circumstances, the person subject to the relief is able to honestly and legally deny the arrest or charge to anyone other than: ÃÂ (1) any court, (2) any federal, state, or local prosecutor, (3) any law enforcement agency, (4) any licensing agency, (5) any licensed school, day care center, or other facility involving children, (6) any government employer or nominating/tenure commission with respect to employment of a judicial or quasi-judicial officer or employment at a senior-level, executive-grade government position. D.C. Code § 16-803.
- Sealing A Conviction: If the motion is granted, the person subject to relief is able to honestly and legally deny the conviction to anyone other than: (1) any court, (2) any federal, state, or local prosecutor, (3) any law enforcement agency, (4) any licensing agency, (5) any licensed school, day care center, or other facility involving children, (6) any government employer or nominating/tenure commission with respect to employment of a judicial or quasi-judicial officer or employment at a senior-level, executive-grade government position. D.C. Code § 16-803.
- Sealing of Juvenile Records: Upon entry of the order, the proceedings will be treated as if they never occurred. D.C. Code § 16-2335.

I'd love to help out on this project!

**Comment by brianek** [comment]
We are adding new items to the to do on the readme page. And it includes a task on this epilogue section you mentioned.
