### ISSUE TITLE
Look into automatic eligibility checker that uses PHP

### ISSUE THREAD

**Issue by brianek** [codefordc/expungement-dc#165]
https://github.com/mhollander/Expungement-Generator.

Is this possible for us to do?

**Comment by brianek** [comment]
http://m.asos.com/mt/us.asos.com/Monki-Checked-Shirt/16zfrd/?iid=5571339&cid=11318&sh=0&pge=2&pgesize=50&sort=3&clr=Navy+multi&totalstyles=443&gridsize=3&mporgp=L01vbmtpL01vbmtpLUNoZWNrZWQtU2hpcnQvUHJvZC8.&un_jtt_v_frompage=2

**Comment by brianek** [comment]
You can  test the PA the site here:   You can log in using test1234@test.com.  The password is test1234.

**Comment by brianek** [comment]
Here is  sample criminal record
[CPReport (54).pdf](https://github.com/codefordc/clean-slate/files/13663/CPReport.54.pdf)

**Comment by brianek** [comment]
[CPReport (53) (1).pdf](https://github.com/codefordc/clean-slate/files/13664/CPReport.53.1.pdf)

**Comment by mchelen** [comment]
Ok looking at those examples, what text needs to be extracted from them?

**Comment by brianek** [comment]
So these attached examples are from PA. I will attache the DC ones I showed you last night. I created a repo. Ill paste the link also.

**Comment by brianek** [comment]
https://github.com/codefordc/Expungement_generatordc

**Comment by brianek** [comment]
[Court Form 2 (3).pdf](https://github.com/codefordc/clean-slate/files/14233/Court.Form.2.3.pdf)
[Court Form 1 (3).pdf](https://github.com/codefordc/clean-slate/files/14234/Court.Form.1.3.pdf)
[MPD Form (3).pdf](https://github.com/codefordc/clean-slate/files/14235/MPD.Form.3.pdf)

**Comment by brianek** [comment]
Above are the DC forms. So the variables to extract are # 1)disposition date 2) crime/charge 3)charge disposition/disposition  And optionally: 1) name 2) PDID

**Comment by brianek** [comment]
@mchelen

**Comment by mchelen** [comment]
@brianek Are these PDFs (Court Form 2 (3).pdf, Court Form 1 (3).pdf, MPD Form (3).pdf) examples of forms that we need to pull information from, or put information into? One issue with these is they all appear to be scanned images, so it's not possible to directly extract text from them.

**Comment by brianek** [comment]
Can't we ocr them? I can also try to convert to word. This is the documents
that will have info taken (pull)from them. The info could then go to a html
page or be provided in a doc. Or pdf.

**Comment by mchelen** [comment]
OCR is possible, but can be much more difficult depending on what info
needs to be extracted. The first step then would be trying some OCR utils
and seeing how the output looks.
It may be worth petitioning DC courts to obtain better formatted PDF files,
but idk how difficult that would be.

**Comment by brianek** [comment]
They give out word documents. Someone scanned it to give to me. I think I
know a good ocr

**Comment by mchelen** [comment]
Can we get the Word documents?

**Comment by brianek** [comment]
Hey Mike: Sorry for the late reply. So here's what I was able to do. I have a program that convert a pdf into html web page or  into word. So I converted them to word and I have added them to this message. 
[Court Form 1 (4).docx](https://github.com/codefordc/clean-slate/files/16302/Court.Form.1.4.docx)
[MPD Form (4).docx](https://github.com/codefordc/clean-slate/files/16303/MPD.Form.4.docx)

**Comment by mchelen** [comment]
@brianek Hey no worries. You can probably see the formatting of these .docx files are in pretty bad shape though. Ideally we would get the original files before they were scanned. Is that possible?

**Comment by brianek** [comment]
Yes. We could get the printed copies and scan them in a form that is easiest for a computer to read. Or we can ask for them in a word format.

**Comment by mchelen** [comment]
@brianek Yeah if at all possible to get the Word files before they are printed, that would be ideal.

**Comment by brianek** [comment]
whats the second best option if that is not possible?

**Comment by brianek** [comment]
@mchelen here is a message I got from the Expungement generator from Phily. I asked him what line of code reads the criminal records. 

To briefly answer your question, the regular expressions from line 100-180 is the code that defines how to read the docket.  The horrible function readArrestRecord is the part that applies the regular expressions and stores everything off into variables.  The function basically takes a line by line look at an arrest record and brute force tries to match that line to one of the aforementioned regular expressions.

readArrestRecord is called in expunge.php, which first calls pdftotext on the pdf docket sheet, which reads the pdf into a text file.  The text file is then fed into readArrestRecord.

Let me know if that helps.

The big challenge that you are going to have is how to OCR the scanned documents.  That is beyond my expertise, but I understand that this is a problem that has been solved by other people.

**Comment by mchelen** [comment]
Yeah the biggest issue is getting the best quality data to start with. What we want ideally are the original document files, or whatever is closest to those files. Each time the files are converted/printed/scanned they become worse quality.
