### ISSUE TITLE
Browser support on older IE?

### ISSUE THREAD

**Issue by jimwebb** [codefordc/expungement-dc#17]
This is just a wacky thought: does anyone know what version of IE the DC Public Library uses on their public computers? I'm guessing it's old IE -- and if it's older than IE9, support for angular.js might be wonky, which might impact how the development happens.

I'm new to this project, so my apologies for asking a question that I don't have an answer to. :)

**Comment by stvnrlly** [comment]
This is a great point. There's information about compatibility in the [Angular docs](https://docs.angularjs.org/guide/ie):

> Note: AngularJS 1.3 has dropped support for IE8. Read more about it on our blog. AngularJS 1.2 will continue to support IE8, but the core team does not plan to spend time addressing issues specific to IE8 or earlier.

I've asked DCPL to tell me what browsers they provide, and will get back if they tell me.

**Comment by stvnrlly** [comment]
I stopped by MLK library: they have IE, Chrome, and Firefox. They couldn't guarantee that the IE will be a recent version, though.

If the project does continue to use Angular, it may be wise to include an alert for people who visit from unsupported browsers.

**Comment by jimwebb** [comment]
I happened by the Petworth branch today: they're running Windows 7 with IE11, Chrome 42, Firefox 26, and Safari 5. All very up-to-date, which is great.
