### ISSUE TITLE
If you arrive at any login page (individual or organization), you can no longer click back to the homepage

### ISSUE THREAD

**Issue by emanuelfeld** [codefordc/expungement-dc#176]

**Comment by brianek** [comment]
Thanks for letting us know

**Comment by rdeprey** [comment]
I think this is related to a mixed content error on the login page.  The login page loads over https, but the page is loading the parse-1.2.12.min.js file over http, which causes Javascript errors.  I submitted a pull request with more details on a hopeful fix.  It worked when I tested it locally, but we won't really know if it works until we test it over https.

**Comment by brianek** [comment]
Fixed. Thanks!!!!!!
