### ISSUE TITLE
Additional to dos.

### ISSUE THREAD

**Issue by brianek** [codefordc/expungement-dc#18]
-Add in a main page. Expunge.io is a great model to use. Two important notes: 1) Make sure to add in a section about  benefits-why you should seal your record. Feel free to add dummy comment and we can insert the 3 top reasons.

**Comment by mattbailey0** [comment]
I just have a sec right now, but each bullet on this should be broken out as an individual issue! That way people can tackle them one by one.

**Comment by brianek** [comment]
I just realized that. and will do so.
