### ISSUE TITLE
Create a menu for our pathways/create a select one or select all menu

### ISSUE THREAD

**Issue by brianek** [codefordc/expungement-dc#45]

**Comment by brianek** [comment]
See page 1 and 2 of this document.

**Comment by brianek** [comment]
@cweems @jrleszcz @jmezetin . Please check the code for DC slack messages. As I have sent out information for tomorrow :-). Happy Memorial Day.

**Comment by jimwebb** [comment]
I think this is complete: https://github.com/codefordc/clean-slate/pull/48
