### ISSUE TITLE
Update route providers and route defintions

### ISSUE THREAD

**Issue by brianek** [codefordc/expungement-dc#46]
Below is the current code. We need to remove legal aid completely and add in after the home page, the "how to get your criminal record" page . In addition, the wizard should take the user to the first menu of wizards.
 Route definition
myApp.config(['$routeProvider',
    function ($routeProvider) {
        $routeProvider
            // Homepage includes Expunge D.C. overview and link to the wizard
            .when('/', {
                templateUrl: 'views/home.html',
                controller: 'homeController'
            })
            // The wizard!
            .when('/eligibility-check', {
                redirectTo: function(routeParams, path, search) {
                    return '/eligibility-check/q/0'
                }
            })
            .when('/eligibility-check/q/:stateName', {
                templateUrl: 'views/eligibility-checker.html',
                controller: 'EligibilityWizardController as eligibilityCtrl'
            })
            // FAQs
            .when('/questions', {
                templateUrl: 'views/questions.html',
                controller: 'questionsController'
            })
            // Legal Aid Page
            .when('/legal-aid', {
                templateUrl: 'views/legal-aid.html',
                controller: 'legalAidController'
            })
            // If the user attempts to visit a route that doesn't match any of the patterns above, re-direct them to the homepage
            .otherwise({
                redirectTo: '/'
            });
}]);

**Comment by RyanGladstone** [comment]
I renamed the "legal aid" route to map to "how to get your criminal record"

**Comment by brianek** [comment]
thanks!
