### ISSUE TITLE
Rebuild progress bar

### ISSUE THREAD

**Issue by jimwebb** [codefordc/expungement-dc#49]
https://github.com/codefordc/clean-slate/pull/48 broke how the progress bar functions, in exchange for providing the functionality of allowing users to follow the five paths from the main page. (The progress bar looked at the question numbers to gauge the user's path; now the numbers are arbitrary and used to denote different sections.)

This needs to be fixed and the progress bar restored to its original working condition.

**Comment by brianek** [comment]
Does anyone want to take this on? Or give me tips on how I can fix it.

**Comment by ave-llan** [comment]
PR #54 fixes this!
