### ISSUE TITLE
Redundant HTTP Requests in EligibilityWizardController

### ISSUE THREAD

**Issue by ave-llan** [codefordc/expungement-dc#59]
`EligibilityWizardController` is doing an HTTP Request for `combined-flow.json` every time the user answers a question.  This also means `executeController()` is being called each time which recalculates the tree height. 

These things should only need to be done once.

**Comment by brianek** [comment]
Thoughts on how this can be fixed?

**Comment by ave-llan** [comment]
I think we just need to add a check to see if it has already been loaded before loading it again.  I'll work on this next chance I get (might not be until tomorrow).  

This has probably been happening since Charlie fixed the 'routing' and the back button about a month ago, so it is not stopping anything from working correctly—it's just not ideal.

**Comment by brianek** [comment]
okay. No rush; if thats the case then it doesn’t have to be fixed by Demo day. Whenever you can get to it is fine! :-)

**Comment by RyanGladstone** [comment]
I'd recommend the combined-flow data should be moved into a service that only makes an HTTP call once.
