### ISSUE TITLE
Simplify list of ineligible crimes; any suggestions on how i can turn this into a simple drop down list specifically for the person viewing the site via their mobile phone?

### ISSUE THREAD

**Issue by brianek** [codefordc/expungement-dc#61]
clean-slate/ineligible-misdemeanors.json

**Comment by brianek** [comment]
@RyanGladstone . Thoughts?

**Comment by RyanGladstone** [comment]
I'm not sure I fully understand the question. 

Are you interested in having all of the ineligible crimes listed in a drop down list / select?

**Comment by brianek** [comment]
sorry about that. I was thinking that we no longer need a search feature. And a simple drop down (but no select option) would suffice. But then I realized that I can just remove the code that has the search box  and that should do the trick!

**Comment by RyanGladstone** [comment]
ah, ok!

**Comment by DavidGinzberg** [comment]
@brianek did that work? or do we need to look into this further?

**Comment by brianek** [comment]
I didn't upload it so we can have someone work on this tonight.
