### ISSUE TITLE
expungement vs sealing 

### ISSUE THREAD

**Issue by justgrimes** [codefordc/expungement-dc#7]
Expungement and record sealing are two very different things. You might want to be more clear which one you are talking about (e.g the app is called "expungement" but you are talking about "sealing" in the description). Is this app checking for both?

**Comment by mattbailey0** [comment]
Well, there isn't really expungement of records in DC.  Obv the app will deal with sealing and the repo name is a little inaccurate.  We should probably look at whether it makes sense to merge this work with the work you did at the hackathon - but I don't want to confuse the folks who are working on it.

**Comment by rebeccawilliams** [comment]
+1 to calling it sealing

**Comment by cweems** [comment]
@justgrimes @mattbailey0 @rebeccawilliams Think I'll mark this closed as we've now re-named the project as Clean Slate.
