### ISSUE TITLE
I broke the site-

### ISSUE THREAD

**Issue by brianek** [codefordc/expungement-dc#70]
if anyone can figure out how to fix it, let me know.

**Comment by brianek** [comment]
I made lots of changes

**Comment by ave-llan** [comment]
@brianek PR #71 fixes the things that were causing problems in the json.  I didn't change any other files.

**Comment by brianek** [comment]
Thanks!!!!

**Comment by DavidGinzberg** [comment]
Seems like this is fixed now. If so, can we close this issue?
