### ISSUE TITLE
Clicking back nav button on first question causes JS error

### ISSUE THREAD

**Issue by DavidGinzberg** [codefordc/expungement-dc#72]
From the [first question](http://codefordc.github.io/clean-slate/#/eligibility-check/q/0) ("Do you have access to your complete criminal record right now?"), clicking the `Back` nav button causes the following error to occur twice in the javascript console:

```
TypeError: Cannot read property 'treeHeight' of undefined
    at self.progressBar (app.js:254)
    at eb.functionCall (angular.js:12299)
    at Object.<anonymous> (angular.js:12702)
    at k.$get.k.$digest (angular.js:14187)
    at k.$get.k.$apply (angular.js:14457)
    at HTMLButtonElement.<anonymous> (angular.js:22908)
    at HTMLButtonElement.c (angular.js:2998)
```

This doesn't seem to directly impact the user (the page momentarily redirects to `~/#/eligibilty-check/q/undefined` and then back to `~/#/eligibilty-check/q/0`, with minimal visible change), but we should clean this up to ensure it doesn't cause trouble down the road.

**Comment by ave-llan** [comment]
I believe this is related to #59 and won't happen once we fix that issue.

**Comment by brianek** [comment]
should I close this issue?

**Comment by DavidGinzberg** [comment]
I'd suggest labeling it as a duplicate and closing it once #59 is fixed (assuming that does fix this). That way it doesn't have to be re-opened if for some reason it isn't resolved.
