### ISSUE TITLE
More descriptive results

### ISSUE THREAD

**Issue by stvnrlly** [codefordc/expungement-dc#8]
Instead of "Eligible" and "Ineligible", a sentence like "You are eligible to have your conviction expunged." would be nice. If the app deals with expungement vs. sealing (as in #7), it could be expanded to "You are ineligible to have your conviction expunged, but you may be able to have your records sealed." or something like that.

**Comment by sarahfathallah** [comment]
Agreed. A short sentence explaining the reason would also be good (though more a nice to have).
