### ISSUE TITLE
Revise Nonconviciton/conviction button. Break it into two and make sure corresponding code is also changed

### ISSUE THREAD

**Issue by brianek** [codefordc/expungement-dc#84]
On the first page you could say,

1)    I have an arrest or charge that resulted in a non-conviction that I would like to seal that does not fit into any of the categories above

2)    I have a conviction that I would like to seal that does not fit into any of the categories above

Then you have to ask if a case is pending. After that it is broken down to felony conviction, misdemeanor conviction for the conviction tab.

**Comment by jmezetin** [comment]
I created a pull request to solve this issue.

**Comment by brianek** [comment]
thanks!
