### ISSUE TITLE
Simplify our definitions. Many words on the site are not defined simply. 

### ISSUE THREAD

**Issue by brianek** [codefordc/expungement-dc#85]
Anyone willing to Add in popup legal glossary using this: http://openadvocate.org/readclearly/? ReadClearly identifies complex legal terms on your website and displays a plain language explanation.

**Comment by cweems** [comment]
@brianek think I've added this correctly in PR #100 ! You might want to pull down and take a look to confirm. Read Clearly doesn't play well with AngularJS so this took a bit of adapting.

**Comment by DavidGinzberg** [comment]
Looks like it doesn't work with https right now; getting mixed content warnings on Chrome and Firefox. Could be a pretty quick fix so I'll see if I can post a patch now.

**Comment by brianek** [comment]
we've been actually looking at the glossary and it actually doesn't include
most legal definitions. So i was wondering would you be willing to use like
a jquery plug-in to have a pop-up definition feature? Or like a drop down
definition box (for example, if we  could put a question mark icon next to
legal words, and the defintion could drop down if the user clicks on the
question mark).

**Comment by stvnrlly** [comment]
@DavidGinzberg it looks like the script is also available over https, so it should be as simple as changing the link to https.

**Comment by brianek** [comment]
@cweems

**Comment by RyanGladstone** [comment]
Submitted a pull request that makes the script call protocol agnostic.

Whether OpenAdvocate is the best long term solution remains an open question.

**Comment by DavidGinzberg** [comment]
@stvnrlly @RyanGladstone looks like you guys took care of it while I was wrestling with SSL on localhost. :+1: :confounded: 

@brianek I'm looking over the readclearly code and documentation to see if we can just inject our own glossary, or if we need to do something from scratch. currently I don't like the highlight color; it makes the text illegible

**Comment by brianek** [comment]
OK great @davidginzberg

**Comment by brianek** [comment]
@DavidGinzberg. Readclearly responded to me to say" ReadClearly installed on an OpenAdvocate website does include two themes, default and neutral (see attached screenshot).  AKA: we can add definitions to the glossary.

**Comment by brianek** [comment]
![screen shot 2015-08-06 at 12 41 05 pm](https://cloud.githubusercontent.com/assets/9157639/9145648/587f1192-3d24-11e5-8086-185db1bdd172.png)

**Comment by DavidGinzberg** [comment]
@brianek I don't quite understand. From what I can see, themes seem to be related to the color scheme of ReadClearly, not having anything to do with the definitions in the glossary. Was there something else in their response about definitions?

**Comment by brianek** [comment]
@DavidGinzberg I think they are saying that you can add definitions to the neutral glossary.

**Comment by brianek** [comment]
yes which we would like to do.

**Comment by rdeprey** [comment]
@DavidGinzberg @brianek I added a line of CSS that adjusts the font color on hover, so that the word being defined is easier to read and submitted it as a PR.
