### ISSUE TITLE
Format definitions page using div span instead of <b>

### ISSUE THREAD

**Issue by brianek** [codefordc/expungement-dc#86]
Format definitions page using the updated definitions in our google doc.https://docs.google.com/document/d/1l1rHyNBNWJMTmBt07U-nhSCzMQNtKSZGve924pvrqIw/edit

**Comment by ParentJA** [comment]
I completed this styling change, however, there are some terms that still need definitions.

**Comment by brianek** [comment]
Yeah, do you want to send me the file. Or I can send you the terms?
