### ISSUE TITLE
 whether or not we can move the json file into a spreadsheet so that it will be easier for the legal partner to edit and update questions.

### ISSUE THREAD

**Issue by brianek** [codefordc/expungement-dc#87]
@John Leszczynski

**Comment by brianek** [comment]
@jrleszcz

**Comment by mchelen** [comment]
The challenge here might be that the question data is hierarchical, so trying to put it in a row/column spreadsheet format could be tricky.
If the data can be entered in a ordered way into a spreadsheet, then it should be technically possible to access it via Javascript.

**Comment by mchelen** [comment]
Here is an example format for a spreadsheet: https://docs.google.com/spreadsheets/d/1zUAFzFqZ3aJPNPLZ9tpHWtEzaTOrC8qOo09dKVFoEMs/edit?usp=sharing

**Comment by ave-llan** [comment]
Here is the Google Sheets API link to get the sheet as a JSON:
https://spreadsheets.google.com/feeds/list/1zUAFzFqZ3aJPNPLZ9tpHWtEzaTOrC8qOo09dKVFoEMs/od6/public/basic?alt=json

**Comment by mchelen** [comment]
Todo:
- [ ] reformat json from spreadsheet to match current json object structure
  - google script or regular javascript?
- [ ] export json to csv for import to spreadsheet
- [ ] spreadsheet data validation?

**Comment by rlh100** [comment]
I am not sure if this helps but it is easy to translate a json file into a PHP array.  $press_url is an API URL (URI?)"

  /\* Call the API with file_get_contents() */
  $press_json = file_get_contents($press_url);

  /\* Convert the JSON results into an array with json_decode() */
  $press_array = json_decode($press_json, true);

Once the data is in an array it is straight forward to convert it to a CSV.

I must admit I am not really a programmer, I hack and hacked this for a calling APIs in PHP talk I gave:
  http://harker.com/Talks/APIintro

RLH

**Comment by brianek** [comment]
Thank you!
