### ISSUE TITLE
Incorporate analytics into our github site

### ISSUE THREAD

**Issue by brianek** [codefordc/expungement-dc#92]
We can either use google analytics or some other analytics site: https://bitdeli.com/

**Comment by DavidGinzberg** [comment]
What kind of analytics are we looking for? What information do we want to gather and why?

**Comment by brianek** [comment]
Ideally the following:
What did they search to get there
what site did they come from before they got our site
unique visitors
how many visits each page (i.e. definitions page vs.“how to get your criminal record”  page)
How many click the button  (i.e. to search for their criminal record online Or  the print button)
How many users are visiting which routes (incorrect ID vs.  fugitive arrests vs. conviction/non-conviction vs. misdemeanor)

**Comment by brianek** [comment]
Some helpful sites/videos: https://www.youtube.com/watch?v=lyOnxr2Zsks: use enhanced attribution links. Google tag manager.

**Comment by stvnrlly** [comment]
IP anonymization is a good idea if you're sending the data through Google: https://developers.google.com/analytics/devguides/collection/analyticsjs/advanced#anonymizeip

**Comment by brianek** [comment]
Basic analytics tracking: http://stackoverflow.com/questions/17207458/how-to-add-google-analytics-tracking-id-to-github-pages
