### ISSUE TITLE
Disable navbar collapse behavior on full-sized screens

### ISSUE THREAD

**Issue by DavidGinzberg** [codefordc/expungement-dc#94]
When viewing the site on desktop or full-sized screens, clicking the navbar causes a horizontal scroll bar to appear and slide up or down. Looking at the DOM, this seems to be a bootstrap navbar-collapse behavior, which we have on mobile. When the navbar doesn't collapse it just looks strange and detracts from the overall quality of the site so we should find a way to prevent it when it's not necessary.

**Steps to reproduce**
1. Go to the [home page](http://codefordc.github.io/clean-slate/)
2. Click the `Home` button repeatedly

**Comment by brianek** [comment]
@ParentJA  Thoughts?

**Comment by ParentJA** [comment]
I'll take a look.

**Comment by brianek** [comment]
Thanks!!!!

**Comment by rdeprey** [comment]
I fixed this and submitted a pull request.

**Comment by brianek** [comment]
@rdeprey @thanks!

**Comment by DavidGinzberg** [comment]
Looks like it's fixed by the pull request from @rdeprey :+1: . I've tested briefly on desktop and emulated mobile devices of several different sizes. Closing the issue.
