### ISSUE TITLE
Configure our domain name to route to the github pages site so that users can find us easily.

### ISSUE THREAD

**Issue by brianek** [codefordc/expungement-dc#96]
We haven't bought the domain yet. If you are interested working on this, let me know!

**Comment by stvnrlly** [comment]
Here's what is necessary: https://help.github.com/articles/adding-a-cname-file-to-your-repository/.

In this case, that would mean:
1. Create a `CNAME` file in the repo root with the contents `cleanslate.com`.
2. Add DNS entries for the new domain (through the registrar's website, not GitHub). Create two `CNAME` records, one for `@` and one for `www`, both pointing at `codefordc.github.io`.

The GitHub documentation itself is confusing, so I also referenced http://stackoverflow.com/questions/9082499/custom-domain-for-github-project-pages.

**Comment by DavidGinzberg** [comment]
@brianek If you like I can take care of this or walk someone through it. I've done this sort of thing for github sites before (see my [Israel blog repo](https://github.com/DavidGinzberg/IsraelFellow) for an example)

By the way which domain do we want? I just looked and [cleanslate.com and .org are taken, and the .net is very expensive](http://who.is/whois/cleanslate.com) but cleanslatedc.com (as suggested by @ParentJA ) and .net are available, or we can look at other options. Possibly information overload, but there are also [lots more TLD options than just a .com or .org](http://tld-list.com/tlds-from-a-z)

**Comment by brianek** [comment]
@DavidGinzberg yes if you could take care of it that would be great. Just an fyi that stvrlly would then like us to change it to https and he is willing to advise on that. I think cleanslatedc.com will work just fine. Let me just countact our legal partner and confirm! She should respond soon!

**Comment by brianek** [comment]
@DavidGinzberg yup we can move forward with cleanslatedc.org!!!

**Comment by DavidGinzberg** [comment]
All set. The site is now visible at cleanslatedc.com thanks to the hard work of @brianek -- and HTTPS is >90% there
